import bassinCacher from '../Images/Bassin_cacher.jpg'
import bassinChemin from '../Images/Bassin_chemin.jpg'
import falaise from '../Images/Falaise.jpg'
import parkTrinite from '../Images/Park_la_trinite.jpg'
import parkLePort from '../Images/Park_le_port.jpg'
import parkSaintPaul from '../Images/Park_saint_paul.jpg'
import traverse from '../Images/Traverser_du_chemin.jpg'
import listeVilles from './ListeVilles'
import listeInstallations from './ListeInstallations'


const listeData = [
  {
    id: "0",
    title: "The Park",
    ville: listeVilles[0],
    mignature: falaise,
    listeImage: [falaise, parkLePort, bassinCacher],
    listeVideo: [],
    installations: [listeInstallations[0], listeInstallations[3], listeInstallations[2]],
    latitude: "-21.062556",
    longitude: "55.538418",
    description: "",
  },
  {
    id: "1",
    title: "Chaudron",
    ville: listeVilles[3],
    mignature: parkTrinite,
    listeImage: [parkLePort, parkTrinite],
    listeVideo: [],
    installations: [listeInstallations[1], listeInstallations[0]],
    latitude: "-21.236841",
    longitude: "55.416323",
    description: "",
  },
  {
    id: "2",
    title: "Park le Port",
    ville: listeVilles[2],
    mignature: parkLePort,
    listeImage: [parkLePort, parkSaintPaul, bassinChemin],
    listeVideo: [],
    installations: [listeInstallations[0], listeInstallations[1], listeInstallations[2]],
    latitude: "-21.231808",
    longitude: "55.672281",
    description: "",
  },
  {
    id: "3",
    title: "Bassin Cacher",
    ville: listeVilles[4],
    mignature: bassinCacher,
    listeImage: [bassinCacher, bassinChemin, falaise],
    listeVideo: [],
    installations: [listeInstallations[1]],
    latitude: "-21.135958",
    longitude: "55.465684",
    description: "",
  },
  {
    id: "4",
    title: "Ocean rouge",
    ville: listeVilles[0],
    mignature: traverse,
    listeImage: [traverse, falaise],
    listeVideo: [],
    installations: [listeInstallations[2], listeInstallations[3]],
    latitude: "-21.077489",
    longitude: "55.542704",
    description: "",
  },
  {
    id: "5",
    title: "Falaise",
    ville: listeVilles[4],
    mignature: falaise,
    listeImage: [falaise, parkLePort],
    listeVideo: [],
    installations: [listeInstallations[0], listeInstallations[2], listeInstallations[3]],
    latitude: "-21.231725",
    longitude: "55.648702",
    description: "",
  },
  {
    id: "6",
    title: "The Park of good",
    ville: listeVilles[7],
    mignature: parkTrinite,
    listeImage: [parkTrinite, parkSaintPaul, parkLePort],
    listeVideo: [],
    installations: [listeInstallations[1], listeInstallations[0], listeInstallations[2]],
    latitude: "-21.123481",
    longitude: "55.483235",
    description: "",
  },
  {
    id: "7",
    title: "Go Go Park",
    ville: listeVilles[3],
    mignature: parkSaintPaul,
    listeImage: [parkSaintPaul, parkTrinite],
    listeVideo: [],
    installations: [listeInstallations[3], listeInstallations[1]],
    latitude: "-21.378437",
    longitude: "55.675833",
    description: "",
  },
  {
    id: "8",
    title: "Barre Park",
    ville: listeVilles[1],
    mignature: parkSaintPaul,
    listeImage: [parkSaintPaul, parkTrinite],
    listeVideo: [],
    installations: [listeInstallations[1], listeInstallations[2], listeInstallations[0]],
    latitude: "-21.129712",
    longitude: "55.468328",
    description: "",
  },
  {
    id: "9",
    title: "Traction Park",
    ville: listeVilles[0],
    mignature: parkLePort,
    listeImage: [parkLePort],
    listeVideo: [],
    installations: [listeInstallations[0]],
    latitude: "-21.281675",
    longitude: "55.40626",
    description: "",
  },
  {
    id: "10",
    title: "All Park",
    ville: listeVilles[6],
    mignature: bassinCacher,
    listeImage: [bassinCacher, parkLePort, parkTrinite, bassinChemin],
    listeVideo: [],
    installations: [listeInstallations[0], listeInstallations[1], listeInstallations[2], listeInstallations[3]],
    latitude: "-21.109687",
    longitude: "55.495977",
    description: "",
  },
  {
    id: "11",
    title: "Bar de fer",
    ville: listeVilles[1],
    mignature: bassinChemin,
    listeImage: [bassinCacher, parkTrinite, bassinChemin],
    listeVideo: [],
    installations: [listeInstallations[0], listeInstallations[1], listeInstallations[2], listeInstallations[3]],
    latitude: "-21.01832",
    longitude: "55.42439",
    description: "",
  },
  {
    id: "12",
    title: "Street Workk",
    ville: listeVilles[0],
    mignature: parkTrinite,
    listeImage: [parkLePort, parkTrinite, bassinChemin],
    listeVideo: [],
    installations: [listeInstallations[0], listeInstallations[1], listeInstallations[3]],
    latitude: "-21.117174",
    longitude: "55.451062",
    description: "",
  },
  {
    id: "13",
    title: "Force Traction",
    ville: listeVilles[3],
    mignature: bassinCacher,
    listeImage: [bassinCacher, parkLePort, parkTrinite, bassinChemin],
    listeVideo: [],
    installations: [listeInstallations[0], listeInstallations[1], listeInstallations[2], listeInstallations[3]],
    latitude: "-20.8869",
    longitude: "55.4510",
    description: "",
  },
  {
    id: "14",
    title: "Perf Park",
    ville: listeVilles[9],
    mignature: bassinCacher,
    listeImage: [bassinCacher, parkLePort, bassinChemin],
    listeVideo: [],
    installations: [listeInstallations[1], listeInstallations[2], listeInstallations[3]],
    latitude: "-21.2425",
    longitude: "55.7089",
    description: "",
  },
];

export default listeData;
